/**:
  ros__parameters:
    replan_period: 0.1
    v_max: 0.4
    v_min: 0.05
    omega_max: 0.3

    MPC_N: 25
    MPC_step_size: 0.25

    safe_dist: 1.3
    gamma_k: 0.3

    kalman_N: 25

    MPC_constraint: "CBF"  #    None Euclidean CBF

    init_N: 1

    # init_v_0: 0.0
    # init_omega_0: 0.0
    
    init_v_0: 0.01
    init_omega_0: 0.3

    init_v_1: 0.01
    init_omega_1: -0.3