/**:
  ros__parameters:
    cylinder_num: 1

    x_0: 2.0
    y_0: 2.0
    z_0: 0.25
    vx_0: 0.0
    # vy_0: 0.0
    vy_0: -0.1

    x_1: -2.0
    y_1: 2.0
    z_1: 0.25
    vx_1: 0.1
    # vy_1: 0.0
    vy_1: -0.1

    x_2: 2.0
    y_2: -2.0
    z_2: 0.25
    vx_2: 0.1
    # vy_2: 0.0
    vy_2: 0.1
    
    x_3: -2.0
    y_3: -2.0
    z_3: 0.25
    vx_3: 0.0
    # vy_3: 0.5
    vy_3: 0.5

    x_4: -2.0
    y_4: -5.0
    z_4: 0.25
    vx_4: 0.0
    # vy_4: 0.0
    vy_4: -0.5
